name: leaflet
description: Wrapper around the leaflet JS 1.5.1 library. 
version: 0.0.1
author: Plamen Todorov <neterror@github.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  js: 0.6.1

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
